from enum import Enum


class Constants:
    EPSILON = '\u30E2'
    EXTENSION = '\u30ED'


class Operators:
    OR = '\u30A5'
    KLEENE = '\u30A1'
    CONCAT = '\u30DF'
    POSITIVE = '\u30E1'
    INTERROGATION = '\u30A3'
    REGREX_OPERATORS = [OR, CONCAT, POSITIVE, INTERROGATION, KLEENE]
    COCOL_REGEX_OPERATORS = [OR, INTERROGATION, KLEENE]

    OPEN_PARENTHESIS = '\u30B1'
    CLOSE_PARENTHESIS = '\u30B2'
    PARENTHESIS_OPERATORS = [OPEN_PARENTHESIS, CLOSE_PARENTHESIS]

    NO_CHECK_OPERATORS = [KLEENE, OR, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, INTERROGATION]

    NO_CONCATENATE_OPERATORS = [OR, OPEN_PARENTHESIS]
    NO_CONCATENATED_OPERATORS = [KLEENE, POSITIVE, INTERROGATION, OR, CLOSE_PARENTHESIS]

    OPERANDS = {KLEENE, CONCAT, POSITIVE, INTERROGATION, OR, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, Constants.EPSILON}
